public class sas {
    public  static void main(String[] args){
        String cock = "IIIIOIIIIASSSWKAIVSSOSSAIIIWKASSVIOSSSAIWKAIIIVSSSOSAIIIWKASVIIIIIIIIIIIIIVSSSSSSSSSSSSSVOSSSAIIIIWKAVSSSSSSSSSSSSVSOSSSAIIWKASSVSSSSSSSVSOIIASSSSSWKAVVIIIIIIIIIVSOSSSSAIWKAIIVOSAIIIWKAIIVIIIIIIIVIIIIIIIIIVIIVSSSSSSSSSSSSVSSSSVSSSVIOSSSAIWKAIIIVSOSSSSAIWKAIIIVSVSSSOSAIIWKAVSSSSSSSVOSSSAIIWKASSVIIIIOSAIIWKAIVSOSAIIIIWKAVSSOSAIIIIWKASVIOSAIIIWKAIVIIIIIIIIIIVSSSSSSSSSSSVSSOSSSAIWKASSVSSOSAIIIIWKAIVSSSSSSSSSSVIIIIIIVSOSSSSAIWKAIIIVOSAIIIWKAIVIIIIIIIIIIIVVOIIASSSWKASSVSSSOSAIIIIWKAVSSSSSSSSSSSSVSSSVSSOSSSAIWKASVOSAIIIWKAIIVIIIVOSSSAIWKASSSSVIVOSSSSAIWKAIIIVSOSSSAIIWKASVIIIIIVSOSAIIIIIWKASVSSOSAIIIIWKAIVSSSSSSSSSSVIIIIIIVSSSVOSSAIIIIIWKAIIIVIIOSSSAIIWKAVSSSVSSSVSVSOSAIIIWKAVSSSSSSSSSSSSVIIIIOSAIIWKAIVSOSAIIIIWKAVIOSSSSSAIWKAIVSSSSSSSSSVOSSSAIWKASVIOSAIIIWKAVIIIIIIIIIIIIIVOSSAIIIIIWKAIIIVSSOSAIIIIWKASVSOSAIIIWKASVIIIIIIIIIIIIIVIIIIIIVOSSSSAIWKAIIIVSSSOSAIIIIWKAVSSSSSVOSSSAIWKASSSSSVSSSOSAIIIIWKASVIIIIOSAIIIWKAVVSSOSSSAIWKASVSSOSAIIIIWKAIVSSSSSSSSSSVIIIIIIVSOSSSSAIWKAIIIVIOSAIIIWKAIVIIIIIIIIIIIVIIIIIIIIVSSSSSSSSSVSOSAIIIIIWKASVIIIIIOSAIIIWKAVIIIVOSSAIIIIIWKAIIIVIOSAIIIWKAIIVOSSSAIWKASVIOSAIIIWKAVIIIIIIIIIVSOSAIIIIIWKASVSSSOSAIIIIWKASVIIOSAIIIWKAIIVIIIVSOSSSAIWKASVIOSAIIIWKAIIVOSSSAIWKASVIOSAIIIWKAVIIIIIIIIIIIIIVOSSAIIIIIWKAIIIVOSAIIIWKAIVIIIIIIVSSSSSSVIIIIIIIIVIIIIIVOSSSSSAIIWKAIIVIIOSSSAIIWKAVSSSOSAIIIWKAVIIOSAIIIIWKAIVSSOSSSAIWKASVOSAIIIWKAIVIIIIIIIIIIIVVOIIASSSWKASSVIIOSAIIIWKAIVSSVOSSSAIWKASSSVOSSSSAIWKAIIIVSSOSAIIIIWKASSVIOSAIIIWKAVIIIIIIIIIIIIIVIIIIIIIVSOSSSSAIWKAIIVSSSOSAIIIIWKAIVSSSSSVIIIVIIIIOSAIIIWKAVOSSSAIWKASSSVOSSSSAIWKAIIIVSOSSSAIIWKASVSSSVOSSSAIWKASSVSSOSAIIIIWKAIVSSSSSSSSSSVIIIIIIVSOSSSSAIWKAIIIVOSAIIIWKAIVSSOSSSAIWKASSSVSSSSSSSSSSSSSVSSOSSSAIWKASVIIOSAIIIWKAVSVVIIIIIIIVSSSVIIIIIVSSSSSSSVSOSSSAIWKASSVOSAIIIWKAIIVSVIIIVOSAIIIWKAIIVIIOSSSAIIWKAVIIIIOSAIIWKAIVSOSAIIIIWKAVSSOSAIIIIWKASVIOSAIIIWKAIVIIIVVOIIASSSWKASSVOSAIIIWKAIVIIIIIIIIIIIVIIIIIIIIIIIVSOSAIIIWKASVIOSSSAIWKAIIIVSSSSSSVIOSSSSAIWKAIIIVOSAIIIWKAIIVIIIVSSOSSSAIWKASVSOSSSAIIWKASSVSSSVIIIIIIIIIIIIIVSSSSSSSSSSSSSVSSOSSSAIWKASVIIOSAIIIWKAVIIIIIIIIIVIIIVOSSAIIIIIWKAIIIVSSOSAIIIIWKAIVSSSSSSSSSSVIIIIIIVSOIIASSSWKAVIIOSSSAIIWKAVOSAIIWKAIVOSSSAIWKAIIIVSSSSSSSSSSVSOSSSAIWKASVIIIIOSAIIWKAIVIOSSAIWKAIIVSSSOSAIIIWKAIVOSAIIIIIWKASVIOSSSSSAIWKAIVIVIIIIIVOSSSSAIWKAIIIVOSAIIIWKAIVSOSAIIIWKAVSOSAIIIIWKASSVOSAIIIIIWKASVIIIVIIIIIIIIIIIIIIVSSSVIIIIIVOSSSSAIWKAIIIVSSOSAIIIIWKASVIOSAIIIWKAIVIIIIIIIIIIIVSSSSSSSSSSSSVSSOSSSAIWKASSVIOSSSSSAIWKAIVIVOSSSAIWKASSSSSVIIOSSSAIIWKAVSSSVSSSVSVSSOSSSAIWKASVOSSAIIIIIIIWKAVSSSSVSSSSSSSSSSSVIOSSSAIWKAIIIVOSAIIIWKASSVIIIIIVSSSSSSSVSOSSSAIWKASSVSOSSSAIIWKAIVIIIIIIIVIIIVSSSSSSSVSSSVSSSSSSVIIIIIIIIIIIIIVOSSAIIIIIWKAIIIVOSAIIIWKAIVIIIIIIIIIIIVVOIIASSSWKASSVSSSOSAIIIIWKAVSSSSSSSSSSSVIIIIVSSSSSSSSVSSOSSSAIWKASVSSSOSAIIWKAVIOSAIIIIIIWKAIVSOSSAIWKASSSVAIIIIIIIIIIVOSSSSSSSAIIWKAVIOSSSAIWKAVIIIIIIIVIOSAIIIWKAVSSOSSSAIWKASVSSOSAIIIIWKAIVSSSSSSSSSSVIIIIIIVSOSSSSAIWKAIIIVSSOSAIIWKAVSSSSSSSSSVAIIIIIIIIIIVASOSSSAIWKASVOSSSSAIIIIIWKAVIIIIVIIVAIOSSSAIIWKAIIVIIIIIIIIIV";
        char[] cockAr = cock.toCharArray();
        for (int i = 0; i < cockAr.length; i++){
            switch (cockAr[i]){
                case'I':{
                    cockAr[i] = '+';
                    break;
                }
                case'S':{
                    cockAr[i] = '-';
                    break;
                }
                case'W':{
                    cockAr[i] = '<';
                    break;
                }
                case'A':{
                    cockAr[i] = '>';
                    break;
                }
                case'K':{
                    cockAr[i] = ']';
                    break;
                }
                case'O':{
                    cockAr[i] = '[';
                    break;
                }
                case'V':{
                    cockAr[i] = '.';
                    break;
                }

            }
        }
        System.out.println(new String(cockAr));
    }
}
