//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public Nullable<System.DateTime> issued_at { get; set; }
        public string equipment { get; set; }
        public string employee { get; set; }
        public Nullable<System.DateTime> Added { get; set; }
        public int id { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Equipment Equipment1 { get; set; }
    }
}
