//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name table from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        Client.ServiceReference1.GetDataResponse GetData(Client.ServiceReference1.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetDataResponse> GetDataAsync(Client.ServiceReference1.GetDataRequest request);
        
        // CODEGEN: Generating message contract since element name table from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddData", ReplyAction="*")]
        Client.ServiceReference1.AddDataResponse AddData(Client.ServiceReference1.AddDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddData", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddDataResponse> AddDataAsync(Client.ServiceReference1.AddDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(Client.ServiceReference1.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string table;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(string table) {
            this.table = table;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(Client.ServiceReference1.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServiceReference1.ArrayOfString[] GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(Client.ServiceReference1.ArrayOfString[] GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddData", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddDataRequestBody Body;
        
        public AddDataRequest() {
        }
        
        public AddDataRequest(Client.ServiceReference1.AddDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string table;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Client.ServiceReference1.ArrayOfString cols;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Client.ServiceReference1.ArrayOfString vals;
        
        public AddDataRequestBody() {
        }
        
        public AddDataRequestBody(string table, Client.ServiceReference1.ArrayOfString cols, Client.ServiceReference1.ArrayOfString vals) {
            this.table = table;
            this.cols = cols;
            this.vals = vals;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference1.AddDataResponseBody Body;
        
        public AddDataResponse() {
        }
        
        public AddDataResponse(Client.ServiceReference1.AddDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddDataResponseBody {
        
        public AddDataResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Client.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.WebService1Soap>, Client.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetDataResponse Client.ServiceReference1.WebService1Soap.GetData(Client.ServiceReference1.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public Client.ServiceReference1.ArrayOfString[] GetData(string table) {
            Client.ServiceReference1.GetDataRequest inValue = new Client.ServiceReference1.GetDataRequest();
            inValue.Body = new Client.ServiceReference1.GetDataRequestBody();
            inValue.Body.table = table;
            Client.ServiceReference1.GetDataResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetDataResponse> Client.ServiceReference1.WebService1Soap.GetDataAsync(Client.ServiceReference1.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetDataResponse> GetDataAsync(string table) {
            Client.ServiceReference1.GetDataRequest inValue = new Client.ServiceReference1.GetDataRequest();
            inValue.Body = new Client.ServiceReference1.GetDataRequestBody();
            inValue.Body.table = table;
            return ((Client.ServiceReference1.WebService1Soap)(this)).GetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.AddDataResponse Client.ServiceReference1.WebService1Soap.AddData(Client.ServiceReference1.AddDataRequest request) {
            return base.Channel.AddData(request);
        }
        
        public void AddData(string table, Client.ServiceReference1.ArrayOfString cols, Client.ServiceReference1.ArrayOfString vals) {
            Client.ServiceReference1.AddDataRequest inValue = new Client.ServiceReference1.AddDataRequest();
            inValue.Body = new Client.ServiceReference1.AddDataRequestBody();
            inValue.Body.table = table;
            inValue.Body.cols = cols;
            inValue.Body.vals = vals;
            Client.ServiceReference1.AddDataResponse retVal = ((Client.ServiceReference1.WebService1Soap)(this)).AddData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.AddDataResponse> Client.ServiceReference1.WebService1Soap.AddDataAsync(Client.ServiceReference1.AddDataRequest request) {
            return base.Channel.AddDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.AddDataResponse> AddDataAsync(string table, Client.ServiceReference1.ArrayOfString cols, Client.ServiceReference1.ArrayOfString vals) {
            Client.ServiceReference1.AddDataRequest inValue = new Client.ServiceReference1.AddDataRequest();
            inValue.Body = new Client.ServiceReference1.AddDataRequestBody();
            inValue.Body.table = table;
            inValue.Body.cols = cols;
            inValue.Body.vals = vals;
            return ((Client.ServiceReference1.WebService1Soap)(this)).AddDataAsync(inValue);
        }
    }
}
