# Generated by Django 3.1.1 on 2021-06-04 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210604_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.rubric'),
        ),
    ]
