# Generated by Django 3.1.1 on 2021-06-04 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210604_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rubNum',
        ),
    ]
