# Generated by Django 3.1.1 on 2021-06-04 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210604_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.rubric'),
        ),
    ]
